---
# .yamllint: YAML linting configuration for Scratchpad Framework
extends: default

rules:
  braces: disable
  brackets: disable
  colons:
    max-spaces-after: 1
    level: error
  comments:
    require-starting-space: true
    min-spaces-from-content: 1
  document-start:
    present: true
    level: warning  # Warn instead of error for missing ---
  document-end: disable
  empty-lines:
    max: 5  # Allow more blank lines in framework content
    max-start: 0
    max-end: 1
  hyphens:
    max-spaces-after: 1
  indentation:
    spaces: 2
    indent-sequences: consistent
  line-length: disable  # AI framework content needs arbitrary line lengths
  new-lines:
    type: unix
  trailing-spaces:
    level: warning  # Warn instead of error for trailing spaces
  truthy:
    level: warning  # Warn instead of error for truthy values
